baseURL = "http://example.org/"
languageCode = "en-us"
title = "A Very Stable Milking Stool"
theme = "stip"
[Author]
    name = "A Very Stable Milking Stool"
    bio = "Feeding all The Mermaids. With all The Kebabs."
[params.colors]
    background = "#F36109"
    circle = "#3942ba"
    foreground = "#c7d0fc"
    hover = "#cd6cf7"

[params]
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/CeleryVase"

    [[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCapl-PQf15W4wiP3v6g9v8A"    

    [[params.links]]
        icon = "twitch"
        title = "Twitch"
        url = "https://www.twitch.tv/stable_milking_stool"   

    [[params.links]]
        icon = "discord"
        title = "Discord"
        url = "https://discord.gg/NDRWjgZkqp"

    [[params.links]]
        icon = "paypal"
        title = "PayPal"
        url = "https://paypal.me/JonesHoward"
    
    [[params.links]]
        icon = "amazon"
        title = "Amazon"
        url = "https://www.amazon.co.uk/hz/wishlist/ls/3HY734U4GTMET?ref_=wl_share"
    
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/CiderGuru/"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:jaunty.stool@gmail.com"